name: Build and publish rxn4chemistry on PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and publish rxn4chemistry on PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Python setup 3.9
      uses: actions/setup-python@v6
      with:
        python-version: 3.9
    - name: Install build package (for packaging)
      run: pip install --upgrade build
    - name: Build dist
      run: python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        skip-existing: true
